import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

import { Gallows } from "../ui/gallows.slint";

export component gameView  {
    // width: 1920px;
    // height: 1080px;

    width: 800px;
    height: 600px;

    //! Properties set from C++
    in property <string> display_word: "_ _ _";
    in property <int> mistakes;
    in property <bool> game_won;
    in property <bool> game_over;
    
    // Callbacks to C++
    callback letter_pressed(string);
    callback reset_game();
    callback home_clicked();

     // Breite/Höhe dynamisch, aber begrenzt
    property<float> scale_factor: min(root.width / 800px, root.height / 600px) / 1.1;

    VerticalLayout {
        alignment: center;

        width: min(root.width, 800px) * scale_factor;
        height: min(root.height, 600px) * scale_factor;

        spacing: min(root.height * 0.01, 16px) / scale_factor;

        Gallows {
            width: 60%;
            height: 80%;
        }

        Text {
            text: display_word;
            font-size: 32px;
            color: white;
            horizontal-alignment: center;
            letter-spacing: 5px;
        }

        // Letter Keyboard
        VerticalBox { 
            for row in [
                ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
                ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
                ["Z", "X", "C", "V", "B", "N", "M"]
            ] : HorizontalBox {
                alignment: center;
                for key in row : Button {
                    text: key;
                    enabled: !game_over;
                    clicked => { root.letter_pressed(key) }
                }
            }
        }

        HorizontalBox {
            Button {
                text: "New Game";
                primary: true;
                clicked => { root.reset_game() }
            }

            Button {
                text: "Home";
                primary: true;
                clicked => { root.home_clicked() }
            }
        }
        
    }
}