import { Button } from "std-widgets.slint";

export component homeView
{ 
    // Callbacks
    callback start_clicked();
    callback settings_clicked();
    callback quit_clicked();
    
    property <length> buttons_padding: 100px;
    property <length> buttons_height: 50px;

    VerticalLayout {     
        alignment: center;

        Text {
            text: "Hangman";
            horizontal-alignment: center;
            letter-spacing: 5px;
            font-size: 80px;
        }
      
        VerticalLayout {   
            // Center Buttons 
            padding-left: buttons_padding;
            padding-right: buttons_padding;

            padding-top: 200px;
            spacing: 20px;

            Button {
                text: "Start";
                height: buttons_height;
                clicked => {
                    root.start_clicked();
                }
            }

            Button {
                text: "Settings";
                height: buttons_height;
                clicked => {
                    root.settings_clicked();
                }
            }

            Button {
                text: "Quit";
                height: buttons_height;
                clicked => {
                    root.quit_clicked();
                }
            }
        }
    }
}