import { SpinBox } from "std-widgets.slint";
export component settingsView
{ 
    callback letterCount(int);

    VerticalLayout {
        alignment: center;
        
        Text {
            text: "Settings";
            horizontal-alignment: center;
            letter-spacing: 5px;
            font-size: 80px;
        }


        SpinBox {
            value: 8;
            minimum: 1;
            maximum: 45;
        }
    }
}