import { Button } from "std-widgets.slint";

import { homeView } from "home.slint";
import { settingsView } from "settings.slint";
import { gameView } from "game.slint";

export component AppWindow inherits Window {
    // Setup
    title: "Hangman";
    min-width: 800px;
    min-height: 600px;

    // Views
    in property<int> current_view;

    // Callbacks for homeView
    callback start_clicked();
    callback settings_clicked();
    callback quit_clicked();

    if (current_view == 0) : homeView { 
        start_clicked => { root.start_clicked(); }
        settings_clicked() => { root.settings_clicked(); }
        quit_clicked => { root.quit_clicked(); }
    }
    
    // Callbacks for gameView


    if (current_view == 1) : gameView { }

    // Callbacks for settingsView
    callback save_clicked();
    callback cancel_clicked();
    
    if (current_view == 2) : settingsView { 
        save_clicked => { root.save_clicked(); }
        cancel_clicked => { root.cancel_clicked(); }
    }
}