import { Button } from "std-widgets.slint";

import { homeView } from "home.slint";
import { settingsView } from "settings.slint";
import { gameView } from "game.slint";

enum View {
    Home,
    Settings,
    Game,
}

export component AppWindow inherits Window {
    // Setup
    title: "Hangman";
    min-width: 800px;
    min-height: 600px;

    // Views
    in-out property <View> active_view: View.Home;

    // Callbacks for homeView
    callback start_clicked();
    callback settings_clicked();
    callback quit_clicked();

    if (active_view == View.Home) : homeView { 
        start_clicked => { root.start_clicked(); }
        settings_clicked() => { root.settings_clicked(); }
        quit_clicked => { root.quit_clicked(); }
    }
    
    if (active_view == View.Game) : gameView { }

    if (active_view == View.Settings) : settingsView { }
}